# This docker-compose.yml is for demonstration purposes. If you run
# docker-compose build && docker-compose up, you will have a local mosquitto
# mqtt server running and a ticker microservice, which is using the
# samm connected to it, publishing a tick message every
# 3 seconds with topic default/tick. You can e.g. use mqtt-spy to monitor these
# messages.
version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
     - "1883:1883"
    networks:
      - service-network
    restart: always
  redis:
    image: redis
    ports:
     - "6379:6379"
    networks:
      - redis-network
    restart: always
  samm-majo:
    depends_on:
      - mqtt
    image: flaneurtv/samm-majo
    build: .
    environment:
      - "LOG_LEVEL=debug"
      - "LOG_LEVEL_MQTT=debug"
      - "NAMESPACE_LISTENER=default"
      - "NAMESPACE_PUBLISHER=default"
    volumes:
      - ./examples:/srv/examples
    working_dir: /srv/examples/test-sender/
    networks:
      - service-network
      - redis-network
    restart: always
  # samm-test-sender:
  #   depends_on:
  #     - mqtt
  #   build: ./examples/test-sender
  #   environment:
  #     - "LOG_LEVEL=debug"
  #     - "LOG_LEVEL_MQTT=debug"
  #     - "NAMESPACE_LISTENER=default"
  #     - "NAMESPACE_PUBLISHER=default"
  #   networks:
  #     - service-network
  #   volumes:
  #     - ./examples/test-sender/:/srv/
  #   restart: always
  samm-ticker:
    depends_on:
      - mqtt
    image: flaneurtv/samm-ticker
    environment:
      - "LOG_LEVEL=error"
      - "LOG_LEVEL_MQTT=error"
      - "NAMESPACE_LISTENER=default"
      - "NAMESPACE_PUBLISHER=default"
    networks:
      - service-network
    restart: always
networks:
  service-network:
  redis-network:
